### ISSUE TITLE
Defect: Integration Tests

### ISSUE THREAD

**Issue by jdhaines** [rropen/SFM#65]
**Topic**
Integrations currently always run after the Frontend Unit Tests and Backend Unit Tests.  The code:

```yml
on:
  workflow_run:
    workflows: ["Backend Unit Tests", "Frontend Unit Tests"]
    branches: dev
    types: completed
```
isn't doing what it's supposed to do.
